### ISSUE TITLE
require-dependencies

### ISSUE THREAD

**Issue by nadirB** [nadirB/atom-antescofo-syntax#8]
[](https://discuss.atom.io/t/depending-on-other-packages/2360)

**Comment by nadirB** [comment]
Salut Clément,

Super ! Ton implémentation fonctionne, en revanche il faudra spécifier de relancer Atom pour que le chargement de `Atom-Package` s'effectue la première fois.  Dans `readme` ? Ou, est-ce qu'on ajoute une notification ? (généralement lors d'un `update` une notification `restart` apparaît.)

Je viens d'implémenter cela dans `atom-antescofo-light-syntax`.  mais il y a quelque chose qui cloche. Dis-moi ce que j'ai omis quand tu as le temps... et puis est-ce nécessaire de le faire pour celui-ci ?

J'ai pu mettre à jour la nouvelle syntaxe dans `base.less`. Est-ce visible de ton côté (comparé au `screenshots` sur github)? (d'ailleurs les liens vers les images dans atom et atom.io sont cassés!?))


Bye

N.

ps. Tu trouveras en pièce attachée le bug qu'il y a eu lors de la mise à jour d' Atom et que j'ai corrigé en comparant avec un template de Atom / Package Generator / Generate Atom Syntax Theme
[atom-antescofo-report.txt](https://github.com/nadirB/atom-antescofo-syntax/files/760838/atom-antescofo-report.txt)

**Comment by cponcelets** [comment]
Je vais regarder ça ce soir (excuses moi je n'avais pas vu ;) )

**Comment by cponcelets** [comment]
Oui pour les images, elles ne sont pas visibles sur atom.
Sinon le rendu est similaire oui, bravo.

**Comment by cponcelets** [comment]
Ok pour le light il fonctionne bien.
Par contre tu as un trait en plus qui n'existe pas dans le theme normal.

**Comment by nadirB** [comment]
merci Clément pour les retours

-As-tu fais la simulation pour en avoir le coeur net ? Car chez-moi le chargement de atom-package se fait à merveille et la barre de progression lors du chargement est un +++ (une fois le theme installé et atom relancé)

- Les traits verticaux ! Encore ! (étonnement, il ne sont pas visible chez-moi sur OS 10.11.1- Atom 1.13.1 x64) Si c'est seulement un trait cela doit être le `View / Toggle soft wrap`

- Oui il y a un souci avec les images selon le forum Atom, il doit y avoir un contournement...

to be continued, slowly but surely...

**Comment by cponcelets** [comment]
Oui, j'ai testé en simulation réelle ;)
